name: molan_edu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^4.3.2 #https://pub.flutter-io.cn/packages/provider
  flutter_screenutil: ^3.1.0 #https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_swiper: ^1.1.6 #https://pub.flutter-io.cn/packages/flutter_swiper
  iconfont: ^0.7.3 #https://pub.dev/packages/iconfont
  cached_network_image: ^2.2.0 #https://pub.flutter-io.cn/packages/cached_network_image
  video_player: ^1.0.0 #https://pub.flutter-io.cn/packages/video_player
  chewie: ^0.12.0 #https://pub.flutter-io.cn/packages/chewie
  sticky_headers: ^0.1.8+1 #https://pub.flutter-io.cn/packages/sticky_headers
  material_segmented_control: ^2.1.0 #https://pub.flutter-io.cn/packages/material_segmented_control
  fl_chart: ^0.12.0 #https://pub.flutter-io.cn/packages/fl_chart
  # IM
  tencent_im_plugin: ^1.1.2 #https://pub.flutter-io.cn/packages/tencent_im_plugin
  dio: ^3.0.10 #https://pub.flutter-io.cn/packages/dio
  dio_http_cache: ^0.2.11 #https://pub.flutter-io.cn/packages/dio_http_cache
  dio_cookie_manager: 1.0.0 #https://pub.flutter-io.cn/packages/dio_cookie_manager
  cookie_jar: ^1.0.1 #https://pub.flutter-io.cn/packages/cookie_jar
  event_bus: ^1.1.1 #https://pub.flutter-io.cn/packages/event_bus
  shared_preferences: '>=0.5.12+2 <2.0.0' #https://pub.flutter-io.cn/packages/shared_preferences
  connectivity: '>=2.0.0 <3.0.0' #https://pub.flutter-io.cn/packages/connectivity
  json_annotation: ^3.0.0 #https://pub.flutter-io.cn/packages?q=json_annotation
  pull_to_refresh: ^1.6.2 #https://pub.flutter-io.cn/packages/pull_to_refresh
  #支付
  fluwx: ^2.4.0 #https://pub.flutter-io.cn/packages/fluwx
  tobias: ^1.7.1+1 #https://pub.flutter-io.cn/packages/tobias

  fluttertoast: ^7.1.1 # toast提示框
  permission_handler: ^5.0.1+1 # 权限处理
  image_gallery_saver: ^1.6.0
  path_provider: ^1.6.24 # 获取文件路径

  webview_flutter: ^1.0.7 #https://pub.flutter-io.cn/packages/webview_flutter
  flutter_easyloading: ^2.1.2 #https://pub.flutter-io.cn/packages/flutter_easyloading
  flutter_material_pickers: ^1.8.1 #https://pub.flutter-io.cn/packages/flutter_material_pickers
  flutter_xupdate: ^1.0.0 #https://pub.flutter-io.cn/packages/flutter_xupdate
  image_pickers: ^1.0.8+7 #https://pub.flutter-io.cn/packages/image_pickers
  flutter_audio_recorder: ^0.5.5 #https://pub.flutter-io.cn/packages/flutter_audio_recorder
  audioplayers: ^0.17.0 #https://pub.flutter-io.cn/packages/audioplayers
  package_info: '>=0.4.3+2 <2.0.0' #https://pub.flutter-io.cn/packages/package_info
  photo_view: ^0.10.3 #https://pub.flutter-io.cn/packages/photo_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0 #https://pub.flutter-io.cn/packages/json_serializable
  build_runner: ^1.10.4 #https://pub.flutter-io.cn/packages/build_runner

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/my_icons/iconfont.ttf
    - family: HappyFont
      fonts:
        - asset: assets/fonts/HappyFont.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/emoji_list.json
    - assets/images/logo.png
    - assets/images/logo_invite.png
    - assets/images/logo_text.png
    - assets/images/demo.png
    - assets/images/placeholder.png
    - assets/images/common/
    - assets/images/course/
    - assets/images/mine/
    - assets/images/home/
    - assets/images/chat/
    - assets/images/tab/
    - assets/images/timetable/
    - assets/images/invite/
    - assets/images/copybook/
    - assets/images/copybook/grid/
    - assets/images/copybook/background/

flutter_intl:
  enabled: true
